#!/system/bin/sh
# mount internal sd
#busybox mount -t vfat /dev/block/mmcblk0p1 /mnt/sdcard
# mount external sd
#busybox mount -t vfat /dev/block/mmcblk1 /mnt/sdcard
#UMS
#busybox echo /dev/block/mmcblk1 > /sys/devices/platform/s3c-usbgadget/gadget/lun1/file
